# Generated by Django 4.2.30 on 2026-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacture',
            options={'ordering': ['created_at'], 'verbose_name': 'Manufacture', 'verbose_name_plural': 'Manufactures'},
        ),
        migrations.AddField(
            model_name='manufacture',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Cabriolet', 'cabriolet'), ('SUV', 'suv'), ('Four Door', 'four_door'), ('Hatchback', 'hatchback'), ('Coupe', 'coupe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
