# Generated by Django 4.2.30 on 2026-09-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_alter_manufacture_options_manufacture_car_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='production_status',
            field=models.CharField(choices=[('Active', 'active'), ('Paused', 'paused'), ('Discontinued', 'discontinued')], default='Active', max_length=20),
        ),
    ]
