# Generated by Django 4.2.30 on 2026-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_manufacture_production_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='car_type',
            field=models.CharField(blank=True, choices=[('cabriolet', 'Cabriolet'), ('suv', 'SUV'), ('four_door', 'Four Door'), ('hatchback', 'Hatchback'), ('coupe', 'Coupe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='country',
            field=models.CharField(choices=[('germany', 'Germany'), ('japan', 'Japan')], max_length=100),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='production_status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('discontinued', 'Discontinued')], default='active', max_length=20),
        ),
    ]
